Repository akaihola/darkgraylib, pull requests merged in 2024-07, with the labels that each got.

#61 The config dump section name is now required
  CHANGES.rst
  src/darkgraylib/config.py
Labels: enhancement

#66 Fix type checking errors in `config` and `diff`
  src/darkgraylib/config.py
  src/darkgraylib/diff.py
Labels: CI/testing/release

#67 Use Graylint for linting this repo
  CHANGES.rst
  pyproject.toml
Labels: CI/testing/release

#64 Report version of calling module not self
  CHANGES.rst
  src/darkgraylib/command_line.py
  src/darkgraylib/tests/test_command_line.py
Labels: bug

#57 Improve docstrings
  src/darkgraylib/git.py
  src/darkgraylib/main.py
Labels: documentation

#63 Release 1.3.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release

#68 Don't use `click`
  src/darkgraylib/config.py
Labels: bug

#69 Release 1.3.1
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release

#70 Adjust types in diff test helpers
  src/darkgraylib/testtools/diff_helpers.py
Labels: CI/testing/release

#71 Release 1.3.2
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release

#72 Use different exit codes for various situations
  CHANGES.rst
  src/darkgraylib/command_line.py
  src/darkgraylib/tests/test_command_line.py
Labels: enhancement

#73 Release 2.0.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release
