Repository akaihola/darkgraylib, pull requests merged in 2024-03, with the labels that each got.

#22 Move unused in graylint to darker
  setup.cfg
  src/darkgraylib/black_diff.py
  src/darkgraylib/chooser.py
  src/darkgraylib/concurrency.py
  src/darkgraylib/config.py
  src/darkgraylib/diff.py
  src/darkgraylib/exceptions.py
  src/darkgraylib/git.py
  src/darkgraylib/help.py
  src/darkgraylib/main.py
  src/darkgraylib/multiline_strings.py
  src/darkgraylib/tests/git_diff_example_output.py
  src/darkgraylib/tests/test_argparse_helpers.py
  src/darkgraylib/tests/test_black_diff.py
  src/darkgraylib/tests/test_chooser.py
  src/darkgraylib/tests/test_command_line.py
  src/darkgraylib/tests/test_concurrency.py
  src/darkgraylib/tests/test_config.py
  src/darkgraylib/tests/test_diff.py
  src/darkgraylib/tests/test_difflib.py
  src/darkgraylib/tests/test_git.py
  src/darkgraylib/tests/test_highlighting.py
  src/darkgraylib/tests/test_multiline_strings.py
  src/darkgraylib/tests/test_stdin_filename.py
  src/darkgraylib/tests/test_utils.py
  src/darkgraylib/tests/test_verification.py
  src/darkgraylib/testtools/clear_black_cache_plugin.py
  src/darkgraylib/testtools/helpers.py
  src/darkgraylib/testtools/mock_argument_parser.py
  src/darkgraylib/utils.py
  src/darkgraylib/verification.py
Labels: enhancement

#23 Allow hyphens for option keys in `pyproject.toml`
  CHANGES.rst
  src/darkgraylib/config.py
  src/darkgraylib/tests/test_config.py
Labels: bug

#25 Limit Black below version 24.2 until incompatibility is resolved
  .github/workflows/python-package.yml
  CHANGES.rst
  setup.cfg
Labels: enhancement

#13 Deal with GitHub usernames containing RTL override
  CHANGES.rst
  release_tools/update_contributors.py
Labels: enhancement

#10 Upgrade NixOS tests to use Python 3.11 on both Linux and macOS
  .github/workflows/python-package.yml
  CHANGES.rst
  default.nix
Labels: enhancement

#17 Add a `News` link on the PyPI page
  setup.cfg
Labels: documentation

#21 Deal with deleted GitHub users in contributors update script
  release_tools/update_contributors.py
Labels: documentation

#26 Organize testing tools so they are usable from Darker tests
  src/darkgraylib/tests/test_diff.py
  src/darkgraylib/tests/test_highlighting.py
  src/darkgraylib/testtools/diff_helpers.py
  src/darkgraylib/testtools/highlighting_helpers.py
Labels: enhancement

#27 Use `lru_cache` clear fixture at test module level
  src/darkgraylib/tests/test_config.py
  src/darkgraylib/testtools/clear_black_cache_plugin.py
Labels: enhancement

#29 Move Git helper tests from Darker
  pytest.ini
  src/darkgraylib/git.py
  src/darkgraylib/tests/test_git.py
  src/darkgraylib/testtools/git_repo_plugin.py
  src/darkgraylib/testtools/helpers.py
Labels: enhancement

#30 Move `utils.py` helpers and unit tests from Darker
  src/darkgraylib/tests/test_utils.py
Labels: enhancement

#31 Drop support for Python 3.7
  .github/workflows/pyupgrade.yml
  release_tools/bump_version.py
  src/darkgraylib/git.py
Labels: enhancement

#32 Provide compatibility with Black 24.2
  CHANGES.rst
  setup.cfg
  src/darkgraylib/black_compat.py
  src/darkgraylib/config.py
  src/darkgraylib/files.py
  src/darkgraylib/tests/test_files.py
  src/darkgraylib/testtools/clear_black_cache_plugin.py
Labels: enhancement

#33 Update `actions/checkout@v3` to `@v4`
  .github/workflows/bandit.yml
  .github/workflows/codespell.yml
  .github/workflows/flake8.yml
  .github/workflows/isort.yml
  .github/workflows/mypy.yml
  .github/workflows/pylint.yml
  .github/workflows/python-package.yml
  .github/workflows/pyupgrade.yml
  .github/workflows/safety.yml
  .github/workflows/test-bump-version.yml
  .github/workflows/test-future.yml
  .github/workflows/yaml-lint.yml
  CHANGES.rst
Labels: enhancement

#35 Rename Darker references to Darkgraylib
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test-bump-version.yml
  .github/workflows/test-future.yml
  .gitignore
  .pre-commit-hooks.yaml
  CONTRIBUTING.rst
  CONTRIBUTORS.rst
  Dockerfile
  README.rst
  contributors.yaml
  default.nix
  release_tools/bump_version.py
  release_tools/update_contributors.py
  src/darkgraylib/command_line.py
  src/darkgraylib/config.py
  src/darkgraylib/git.py
  src/darkgraylib/tests/test_command_line.py
  src/darkgraylib/tests/test_highlighting.py
  src/darkgraylib/testtools/clear_black_cache_plugin.py
  src/darkgraylib/version.py
Labels: documentation

#37 Release version 1.0.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  CONTRIBUTING.rst
  README.rst
  pyproject.toml
  setup.cfg
  src/darkgraylib/version.py
Labels: enhancement

#38 Add rename file for git ops
  CHANGES.rst
  src/darkgraylib/testtools/git_repo_plugin.py
Labels: CI/testing

#39 Remove `bump_version.py`, use `darkgray_bump_version` from `darkgray-dev-tools`
  .github/workflows/test-bump-version.yml
  .yamllint
  CHANGES.rst
  release_tools/bump-version-patterns.yaml
  release_tools/bump_version.py
  setup.cfg
Labels: CI/testing/release

#40 Add @Svenito as a contributor
  CONTRIBUTORS.rst
  README.rst
  contributors.yaml
Labels: documentation

#41 Add return type to `GitRepoFixture.rename()`
  src/darkgraylib/testtools/git_repo_plugin.py
Labels: CI/testing/release

#42 Release 1.1.0
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release

#43 Install `darkgray-dev-tools` from PyPI
  CHANGES.rst
  setup.cfg
Labels: bug

#45 Add support for Python 3.12
  .github/workflows/python-package.yml
  CHANGES.rst
  pyproject.toml
  setup.cfg
Labels: enhancement

#46 Small CI build fixes
  .github/workflows/python-package.yml
  .github/workflows/test-future.yml
Labels: CI/testing/release

#44 Drop dependency on Black, isort, flynt & regex
  .github/workflows/mypy.yml
  .github/workflows/pylint.yml
  .github/workflows/python-package.yml
  .github/workflows/test-future.yml
  CHANGES.rst
  constraints-future.txt
  constraints-oldest.txt
  mypy.ini
  setup.cfg
  src/darkgraylib/diff.py
  src/darkgraylib/tests/test_files.py
Labels: enhancement

#49 Skip tests on Python 3.13-dev in Windows and macOS
  .github/workflows/python-package.yml
  CHANGES.rst
Labels: CI/testing/release

#48 Escape pipe pipe symbols in generated readme help output
  CHANGES.rst
  src/darkgraylib/argparse_helpers.py
Labels: documentation

#50 Bump to version 1.1.1
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGES.rst
  README.rst
  src/darkgraylib/version.py
Labels: CI/testing/release

#53 "Configuration loaded" hook
  CHANGES.rst
  src/darkgraylib/command_line.py
  src/darkgraylib/tests/test_command_line.py
Labels: enhancement

#52 Move update-contributors script to the separate development tools package
  CHANGES.rst
  contributors.yaml
  release_tools/__init__.py
  release_tools/update_contributors.py
  setup.cfg
Labels: CI/testing/release

#51 Fix README badge links
  CHANGES.rst
  README.rst
Labels: documentation

#36 Update Black and isort in pre-commit configuration
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  README.rst
Labels: enhancement
